mongo:
    image: mongo:3.6.2
    ports:
        - "27017:27017"

api:
    image: gitlab.labranet.jamk.fi:4567/yts18k1/todo_api
    links:
        - mongo
    environment:
        - MONGODB_URL=mongodb://mongo:27017/todoapp
        - APP_URL=http://18.196.188.140
    ports:
        - "3000:3000"
    restart: "on-failure:10"

app:
    image: gitlab.labranet.jamk.fi:4567/yts18k1/todo_app
    ports: 
        - "80:80"
